/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface HLConstantsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIMIT_ORDER_TIF_ALO"
      | "LIMIT_ORDER_TIF_GTC"
      | "LIMIT_ORDER_TIF_IOC"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LIMIT_ORDER_TIF_ALO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIMIT_ORDER_TIF_GTC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIMIT_ORDER_TIF_IOC",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LIMIT_ORDER_TIF_ALO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIMIT_ORDER_TIF_GTC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIMIT_ORDER_TIF_IOC",
    data: BytesLike
  ): Result;
}

export interface HLConstants extends BaseContract {
  connect(runner?: ContractRunner | null): HLConstants;
  waitForDeployment(): Promise<this>;

  interface: HLConstantsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIMIT_ORDER_TIF_ALO: TypedContractMethod<[], [bigint], "view">;

  LIMIT_ORDER_TIF_GTC: TypedContractMethod<[], [bigint], "view">;

  LIMIT_ORDER_TIF_IOC: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIMIT_ORDER_TIF_ALO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIMIT_ORDER_TIF_GTC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIMIT_ORDER_TIF_IOC"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
