/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFlashBorrower,
  IFlashBorrowerInterface,
} from "../../../../../../lib/valantis-core/src/pools/interfaces/IFlashBorrower";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onFlashLoan",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFlashBorrower__factory {
  static readonly abi = _abi;
  static createInterface(): IFlashBorrowerInterface {
    return new Interface(_abi) as IFlashBorrowerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFlashBorrower {
    return new Contract(address, _abi, runner) as unknown as IFlashBorrower;
  }
}
