/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoreDepositWallet,
  ICoreDepositWalletInterface,
} from "../../../../../lib/hyper-evm-lib/src/interfaces/ICoreDepositWallet";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "destinationDex",
        type: "uint32",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "destinationDex",
        type: "uint32",
      },
    ],
    name: "depositFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICoreDepositWallet__factory {
  static readonly abi = _abi;
  static createInterface(): ICoreDepositWalletInterface {
    return new Interface(_abi) as ICoreDepositWalletInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICoreDepositWallet {
    return new Contract(address, _abi, runner) as unknown as ICoreDepositWallet;
  }
}
