/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICoreDepositWallet__factory } from "./ICoreDepositWallet__factory";
export { ICoreWriter__factory } from "./ICoreWriter__factory";
export { ITokenRegistry__factory } from "./ITokenRegistry__factory";
