/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenRegistry,
  ITokenRegistryInterface,
} from "../../../../../lib/hyper-evm-lib/src/interfaces/ITokenRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "evmContract",
        type: "address",
      },
    ],
    name: "getTokenIndex",
    outputs: [
      {
        internalType: "uint32",
        name: "index",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenRegistryInterface {
    return new Interface(_abi) as ITokenRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenRegistry {
    return new Contract(address, _abi, runner) as unknown as ITokenRegistry;
  }
}
