/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICoreWriter,
  ICoreWriterInterface,
} from "../../../../src/modules/LendingModule.sol/ICoreWriter";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "sendRawAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICoreWriter__factory {
  static readonly abi = _abi;
  static createInterface(): ICoreWriterInterface {
    return new Interface(_abi) as ICoreWriterInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICoreWriter {
    return new Contract(address, _abi, runner) as unknown as ICoreWriter;
  }
}
