/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICoreWriter__factory } from "./ICoreWriter__factory";
export { LendingModule__factory } from "./LendingModule__factory";
