/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISwapFeeModule } from "./ISwapFeeModule";
export type { ISwapFeeModuleMinimal } from "./ISwapFeeModuleMinimal";
