/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export type SwapFeeModuleDataStruct = {
  feeInBips: BigNumberish;
  internalContext: BytesLike;
};

export type SwapFeeModuleDataStructOutput = [
  feeInBips: bigint,
  internalContext: string
] & { feeInBips: bigint; internalContext: string };

export interface ISwapFeeModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callbackOnSwapEnd(uint256,int24,uint256,uint256,(uint256,bytes))"
      | "callbackOnSwapEnd(uint256,uint256,uint256,(uint256,bytes))"
      | "getSwapFeeInBips"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callbackOnSwapEnd(uint256,int24,uint256,uint256,(uint256,bytes))",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      SwapFeeModuleDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackOnSwapEnd(uint256,uint256,uint256,(uint256,bytes))",
    values: [BigNumberish, BigNumberish, BigNumberish, SwapFeeModuleDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapFeeInBips",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "callbackOnSwapEnd(uint256,int24,uint256,uint256,(uint256,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackOnSwapEnd(uint256,uint256,uint256,(uint256,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapFeeInBips",
    data: BytesLike
  ): Result;
}

export interface ISwapFeeModule extends BaseContract {
  connect(runner?: ContractRunner | null): ISwapFeeModule;
  waitForDeployment(): Promise<this>;

  interface: ISwapFeeModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "callbackOnSwapEnd(uint256,int24,uint256,uint256,(uint256,bytes))": TypedContractMethod<
    [
      _effectiveFee: BigNumberish,
      _spotPriceTick: BigNumberish,
      _amountInUsed: BigNumberish,
      _amountOut: BigNumberish,
      _swapFeeModuleData: SwapFeeModuleDataStruct
    ],
    [void],
    "nonpayable"
  >;

  "callbackOnSwapEnd(uint256,uint256,uint256,(uint256,bytes))": TypedContractMethod<
    [
      _effectiveFee: BigNumberish,
      _amountInUsed: BigNumberish,
      _amountOut: BigNumberish,
      _swapFeeModuleData: SwapFeeModuleDataStruct
    ],
    [void],
    "nonpayable"
  >;

  getSwapFeeInBips: TypedContractMethod<
    [
      _tokenIn: AddressLike,
      _tokenOut: AddressLike,
      _amountIn: BigNumberish,
      _user: AddressLike,
      _swapFeeModuleContext: BytesLike
    ],
    [SwapFeeModuleDataStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callbackOnSwapEnd(uint256,int24,uint256,uint256,(uint256,bytes))"
  ): TypedContractMethod<
    [
      _effectiveFee: BigNumberish,
      _spotPriceTick: BigNumberish,
      _amountInUsed: BigNumberish,
      _amountOut: BigNumberish,
      _swapFeeModuleData: SwapFeeModuleDataStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackOnSwapEnd(uint256,uint256,uint256,(uint256,bytes))"
  ): TypedContractMethod<
    [
      _effectiveFee: BigNumberish,
      _amountInUsed: BigNumberish,
      _amountOut: BigNumberish,
      _swapFeeModuleData: SwapFeeModuleDataStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSwapFeeInBips"
  ): TypedContractMethod<
    [
      _tokenIn: AddressLike,
      _tokenOut: AddressLike,
      _amountIn: BigNumberish,
      _user: AddressLike,
      _swapFeeModuleContext: BytesLike
    ],
    [SwapFeeModuleDataStructOutput],
    "nonpayable"
  >;

  filters: {};
}
