/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export type SwapFeeModuleDataStruct = {
  feeInBips: BigNumberish;
  internalContext: BytesLike;
};

export type SwapFeeModuleDataStructOutput = [
  feeInBips: bigint,
  internalContext: string
] & { feeInBips: bigint; internalContext: string };

export interface ISwapFeeModuleMinimalInterface extends Interface {
  getFunction(nameOrSignature: "getSwapFeeInBips"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSwapFeeInBips",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSwapFeeInBips",
    data: BytesLike
  ): Result;
}

export interface ISwapFeeModuleMinimal extends BaseContract {
  connect(runner?: ContractRunner | null): ISwapFeeModuleMinimal;
  waitForDeployment(): Promise<this>;

  interface: ISwapFeeModuleMinimalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSwapFeeInBips: TypedContractMethod<
    [
      _tokenIn: AddressLike,
      _tokenOut: AddressLike,
      _amountIn: BigNumberish,
      _user: AddressLike,
      _swapFeeModuleContext: BytesLike
    ],
    [SwapFeeModuleDataStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSwapFeeInBips"
  ): TypedContractMethod<
    [
      _tokenIn: AddressLike,
      _tokenOut: AddressLike,
      _amountIn: BigNumberish,
      _user: AddressLike,
      _swapFeeModuleContext: BytesLike
    ],
    [SwapFeeModuleDataStructOutput],
    "nonpayable"
  >;

  filters: {};
}
