/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOracleModule,
  IOracleModuleInterface,
} from "../../../src/interfaces/IOracleModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
    ],
    name: "getCurrentPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "priceX96",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
    ],
    name: "getLatestSnapshot",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "priceX96",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "l1BlockNumber",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IOracleModule.OracleSnapshot",
        name: "snapshot",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "priceX96",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxDeviationBps",
        type: "uint256",
      },
    ],
    name: "isPriceValid",
    outputs: [
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
    ],
    name: "snapshotPrice",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "priceX96",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "l1BlockNumber",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IOracleModule.OracleSnapshot",
        name: "snapshot",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOracleModule__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleModuleInterface {
    return new Interface(_abi) as IOracleModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOracleModule {
    return new Contract(address, _abi, runner) as unknown as IOracleModule;
  }
}
