/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IQuoteValidator,
  IQuoteValidatorInterface,
} from "../../../src/interfaces/IQuoteValidator";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "quoteId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "QuoteExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "quoteId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "QuoteRejected",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenIn",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenOut",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMin",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "executionPriceX96",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "oracleSnapshotPriceX96",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "oracleL1Block",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "expirationBlock",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "intendedUser",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "maxDeviationBps",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "quoteId",
            type: "bytes32",
          },
        ],
        internalType: "struct IQuoteValidator.Quote",
        name: "quote",
        type: "tuple",
      },
    ],
    name: "executeQuote",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenIn",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenOut",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMin",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "executionPriceX96",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "oracleSnapshotPriceX96",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "oracleL1Block",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "expirationBlock",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "intendedUser",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "maxDeviationBps",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "quoteId",
            type: "bytes32",
          },
        ],
        internalType: "struct IQuoteValidator.Quote",
        name: "quote",
        type: "tuple",
      },
    ],
    name: "hasOracleDrifted",
    outputs: [
      {
        internalType: "bool",
        name: "drifted",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenIn",
            type: "address",
          },
          {
            internalType: "address",
            name: "tokenOut",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMin",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "executionPriceX96",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "oracleSnapshotPriceX96",
            type: "uint256",
          },
          {
            internalType: "uint64",
            name: "oracleL1Block",
            type: "uint64",
          },
          {
            internalType: "uint256",
            name: "expirationBlock",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "intendedUser",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "maxDeviationBps",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "quoteId",
            type: "bytes32",
          },
        ],
        internalType: "struct IQuoteValidator.Quote",
        name: "quote",
        type: "tuple",
      },
    ],
    name: "validateQuote",
    outputs: [
      {
        internalType: "bool",
        name: "valid",
        type: "bool",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IQuoteValidator__factory {
  static readonly abi = _abi;
  static createInterface(): IQuoteValidatorInterface {
    return new Interface(_abi) as IQuoteValidatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IQuoteValidator {
    return new Contract(address, _abi, runner) as unknown as IQuoteValidator;
  }
}
