/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export type ALMLiquidityQuoteInputStruct = {
  isZeroToOne: boolean;
  amountInMinusFee: BigNumberish;
  feeInBips: BigNumberish;
  sender: AddressLike;
  recipient: AddressLike;
  tokenOutSwap: AddressLike;
};

export type ALMLiquidityQuoteInputStructOutput = [
  isZeroToOne: boolean,
  amountInMinusFee: bigint,
  feeInBips: bigint,
  sender: string,
  recipient: string,
  tokenOutSwap: string
] & {
  isZeroToOne: boolean;
  amountInMinusFee: bigint;
  feeInBips: bigint;
  sender: string;
  recipient: string;
  tokenOutSwap: string;
};

export type ALMLiquidityQuoteStruct = {
  isCallbackOnSwap: boolean;
  amountOut: BigNumberish;
  amountInFilled: BigNumberish;
};

export type ALMLiquidityQuoteStructOutput = [
  isCallbackOnSwap: boolean,
  amountOut: bigint,
  amountInFilled: bigint
] & { isCallbackOnSwap: boolean; amountOut: bigint; amountInFilled: bigint };

export interface ISovereignALMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLiquidityQuote"
      | "onDepositLiquidityCallback"
      | "onSwapCallback"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLiquidityQuote",
    values: [ALMLiquidityQuoteInputStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onDepositLiquidityCallback",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onSwapCallback",
    values: [boolean, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLiquidityQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDepositLiquidityCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onSwapCallback",
    data: BytesLike
  ): Result;
}

export interface ISovereignALM extends BaseContract {
  connect(runner?: ContractRunner | null): ISovereignALM;
  waitForDeployment(): Promise<this>;

  interface: ISovereignALMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLiquidityQuote: TypedContractMethod<
    [
      _almLiquidityQuoteInput: ALMLiquidityQuoteInputStruct,
      _externalContext: BytesLike,
      _verifierData: BytesLike
    ],
    [ALMLiquidityQuoteStructOutput],
    "nonpayable"
  >;

  onDepositLiquidityCallback: TypedContractMethod<
    [_amount0: BigNumberish, _amount1: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;

  onSwapCallback: TypedContractMethod<
    [_isZeroToOne: boolean, _amountIn: BigNumberish, _amountOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLiquidityQuote"
  ): TypedContractMethod<
    [
      _almLiquidityQuoteInput: ALMLiquidityQuoteInputStruct,
      _externalContext: BytesLike,
      _verifierData: BytesLike
    ],
    [ALMLiquidityQuoteStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onDepositLiquidityCallback"
  ): TypedContractMethod<
    [_amount0: BigNumberish, _amount1: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onSwapCallback"
  ): TypedContractMethod<
    [_isZeroToOne: boolean, _amountIn: BigNumberish, _amountOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
