/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICoreDepositWallet } from "./ICoreDepositWallet";
export type { ICoreWriter } from "./ICoreWriter";
export type { ITokenRegistry } from "./ITokenRegistry";
