/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as common from "./common";
export type { common };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CoreWriterLib } from "./CoreWriterLib";
export type { PrecompileLib } from "./PrecompileLib";
