/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TwoSpeedEWMA {
  export type EWMAStateStruct = {
    fastEWMA: BigNumberish;
    slowEWMA: BigNumberish;
    fastVar: BigNumberish;
    slowVar: BigNumberish;
    fastAlpha: BigNumberish;
    slowAlpha: BigNumberish;
    lastUpdateTime: BigNumberish;
    initialized: boolean;
  };

  export type EWMAStateStructOutput = [
    fastEWMA: bigint,
    slowEWMA: bigint,
    fastVar: bigint,
    slowVar: bigint,
    fastAlpha: bigint,
    slowAlpha: bigint,
    lastUpdateTime: bigint,
    initialized: boolean
  ] & {
    fastEWMA: bigint;
    slowEWMA: bigint;
    fastVar: bigint;
    slowVar: bigint;
    fastAlpha: bigint;
    slowAlpha: bigint;
    lastUpdateTime: bigint;
    initialized: boolean;
  };
}

export declare namespace YieldTracker {
  export type YieldComparisonStruct = {
    almYieldBps: BigNumberish;
    lendingYieldBps: BigNumberish;
    smoothedAlmYieldBps: BigNumberish;
    yieldDifferenceBps: BigNumberish;
    almBetter: boolean;
  };

  export type YieldComparisonStructOutput = [
    almYieldBps: bigint,
    lendingYieldBps: bigint,
    smoothedAlmYieldBps: bigint,
    yieldDifferenceBps: bigint,
    almBetter: boolean
  ] & {
    almYieldBps: bigint;
    lendingYieldBps: bigint;
    smoothedAlmYieldBps: bigint;
    yieldDifferenceBps: bigint;
    almBetter: boolean;
  };
}

export interface YieldOptimizerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "alm"
      | "almAllocationBps"
      | "almYieldState"
      | "checkRebalance"
      | "executeRebalance"
      | "getCurrentALMYield"
      | "getLendingYield"
      | "getSmoothedALMYield"
      | "getTotalCapital"
      | "getTrackingStats"
      | "getYieldComparison"
      | "initializeTracking"
      | "isActive"
      | "lastRebalanceTime"
      | "lendingModule"
      | "owner"
      | "pendingOwner"
      | "rebalanceThresholdBps"
      | "recordSwapFees"
      | "renounceOwnership"
      | "setALM"
      | "setActive"
      | "setLendingModule"
      | "setRebalanceThreshold"
      | "token"
      | "tokenIndex"
      | "transferOwnership"
      | "updateLiquidity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ALMUpdated"
      | "AllocationUpdated"
      | "LendingModuleUpdated"
      | "OptimizerActivated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "RebalanceExecuted"
      | "ThresholdUpdated"
      | "YieldUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "alm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "almAllocationBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "almYieldState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkRebalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeRebalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentALMYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSmoothedALMYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrackingStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldComparison",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeTracking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastRebalanceTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lendingModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceThresholdBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordSwapFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setALM", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "setActive", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setLendingModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRebalanceThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidity",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "alm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "almAllocationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "almYieldState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentALMYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSmoothedALMYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrackingStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getYieldComparison",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeTracking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastRebalanceTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lendingModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceThresholdBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSwapFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setALM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLendingModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRebalanceThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidity",
    data: BytesLike
  ): Result;
}

export namespace ALMUpdatedEvent {
  export type InputTuple = [newALM: AddressLike];
  export type OutputTuple = [newALM: string];
  export interface OutputObject {
    newALM: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllocationUpdatedEvent {
  export type InputTuple = [newAlmAllocationBps: BigNumberish];
  export type OutputTuple = [newAlmAllocationBps: bigint];
  export interface OutputObject {
    newAlmAllocationBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LendingModuleUpdatedEvent {
  export type InputTuple = [newLendingModule: AddressLike];
  export type OutputTuple = [newLendingModule: string];
  export interface OutputObject {
    newLendingModule: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptimizerActivatedEvent {
  export type InputTuple = [active: boolean];
  export type OutputTuple = [active: boolean];
  export interface OutputObject {
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceExecutedEvent {
  export type InputTuple = [
    almYieldBps: BigNumberish,
    lendingYieldBps: BigNumberish,
    amountMoved: BigNumberish,
    movedToLending: boolean
  ];
  export type OutputTuple = [
    almYieldBps: bigint,
    lendingYieldBps: bigint,
    amountMoved: bigint,
    movedToLending: boolean
  ];
  export interface OutputObject {
    almYieldBps: bigint;
    lendingYieldBps: bigint;
    amountMoved: bigint;
    movedToLending: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [newThresholdBps: BigNumberish];
  export type OutputTuple = [newThresholdBps: bigint];
  export interface OutputObject {
    newThresholdBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldUpdatedEvent {
  export type InputTuple = [
    almYieldBps: BigNumberish,
    smoothedAlmYieldBps: BigNumberish,
    lendingYieldBps: BigNumberish
  ];
  export type OutputTuple = [
    almYieldBps: bigint,
    smoothedAlmYieldBps: bigint,
    lendingYieldBps: bigint
  ];
  export interface OutputObject {
    almYieldBps: bigint;
    smoothedAlmYieldBps: bigint;
    lendingYieldBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldOptimizer extends BaseContract {
  connect(runner?: ContractRunner | null): YieldOptimizer;
  waitForDeployment(): Promise<this>;

  interface: YieldOptimizerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  alm: TypedContractMethod<[], [string], "view">;

  almAllocationBps: TypedContractMethod<[], [bigint], "view">;

  almYieldState: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        TwoSpeedEWMA.EWMAStateStructOutput,
        boolean
      ] & {
        cumulativeFees: bigint;
        cumulativeLiquidity: bigint;
        lastLiquidity: bigint;
        lastUpdateTime: bigint;
        trackingStartTime: bigint;
        yieldEWMA: TwoSpeedEWMA.EWMAStateStructOutput;
        initialized: boolean;
      }
    ],
    "view"
  >;

  checkRebalance: TypedContractMethod<
    [],
    [
      [boolean, boolean, bigint] & {
        shouldRebalance: boolean;
        moveToLending: boolean;
        suggestedAmount: bigint;
      }
    ],
    "view"
  >;

  executeRebalance: TypedContractMethod<[], [void], "nonpayable">;

  getCurrentALMYield: TypedContractMethod<[], [bigint], "view">;

  getLendingYield: TypedContractMethod<[], [bigint], "view">;

  getSmoothedALMYield: TypedContractMethod<[], [bigint], "view">;

  getTotalCapital: TypedContractMethod<[], [bigint], "view">;

  getTrackingStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalFees: bigint;
        avgLiquidity: bigint;
        trackingDuration: bigint;
      }
    ],
    "view"
  >;

  getYieldComparison: TypedContractMethod<
    [],
    [YieldTracker.YieldComparisonStructOutput],
    "view"
  >;

  initializeTracking: TypedContractMethod<
    [initialLiquidity: BigNumberish],
    [void],
    "nonpayable"
  >;

  isActive: TypedContractMethod<[], [boolean], "view">;

  lastRebalanceTime: TypedContractMethod<[], [bigint], "view">;

  lendingModule: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  rebalanceThresholdBps: TypedContractMethod<[], [bigint], "view">;

  recordSwapFees: TypedContractMethod<
    [feeAmount: BigNumberish, newLiquidity: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setALM: TypedContractMethod<[newALM: AddressLike], [void], "nonpayable">;

  setActive: TypedContractMethod<[active: boolean], [void], "nonpayable">;

  setLendingModule: TypedContractMethod<
    [newLendingModule: AddressLike],
    [void],
    "nonpayable"
  >;

  setRebalanceThreshold: TypedContractMethod<
    [newThresholdBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  tokenIndex: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateLiquidity: TypedContractMethod<
    [newLiquidity: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "alm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "almAllocationBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "almYieldState"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        TwoSpeedEWMA.EWMAStateStructOutput,
        boolean
      ] & {
        cumulativeFees: bigint;
        cumulativeLiquidity: bigint;
        lastLiquidity: bigint;
        lastUpdateTime: bigint;
        trackingStartTime: bigint;
        yieldEWMA: TwoSpeedEWMA.EWMAStateStructOutput;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkRebalance"
  ): TypedContractMethod<
    [],
    [
      [boolean, boolean, bigint] & {
        shouldRebalance: boolean;
        moveToLending: boolean;
        suggestedAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeRebalance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentALMYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLendingYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSmoothedALMYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalCapital"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTrackingStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalFees: bigint;
        avgLiquidity: bigint;
        trackingDuration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getYieldComparison"
  ): TypedContractMethod<
    [],
    [YieldTracker.YieldComparisonStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeTracking"
  ): TypedContractMethod<
    [initialLiquidity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastRebalanceTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lendingModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalanceThresholdBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordSwapFees"
  ): TypedContractMethod<
    [feeAmount: BigNumberish, newLiquidity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setALM"
  ): TypedContractMethod<[newALM: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<[active: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingModule"
  ): TypedContractMethod<[newLendingModule: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRebalanceThreshold"
  ): TypedContractMethod<[newThresholdBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLiquidity"
  ): TypedContractMethod<[newLiquidity: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ALMUpdated"
  ): TypedContractEvent<
    ALMUpdatedEvent.InputTuple,
    ALMUpdatedEvent.OutputTuple,
    ALMUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AllocationUpdated"
  ): TypedContractEvent<
    AllocationUpdatedEvent.InputTuple,
    AllocationUpdatedEvent.OutputTuple,
    AllocationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LendingModuleUpdated"
  ): TypedContractEvent<
    LendingModuleUpdatedEvent.InputTuple,
    LendingModuleUpdatedEvent.OutputTuple,
    LendingModuleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OptimizerActivated"
  ): TypedContractEvent<
    OptimizerActivatedEvent.InputTuple,
    OptimizerActivatedEvent.OutputTuple,
    OptimizerActivatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceExecuted"
  ): TypedContractEvent<
    RebalanceExecutedEvent.InputTuple,
    RebalanceExecutedEvent.OutputTuple,
    RebalanceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "YieldUpdated"
  ): TypedContractEvent<
    YieldUpdatedEvent.InputTuple,
    YieldUpdatedEvent.OutputTuple,
    YieldUpdatedEvent.OutputObject
  >;

  filters: {
    "ALMUpdated(address)": TypedContractEvent<
      ALMUpdatedEvent.InputTuple,
      ALMUpdatedEvent.OutputTuple,
      ALMUpdatedEvent.OutputObject
    >;
    ALMUpdated: TypedContractEvent<
      ALMUpdatedEvent.InputTuple,
      ALMUpdatedEvent.OutputTuple,
      ALMUpdatedEvent.OutputObject
    >;

    "AllocationUpdated(uint256)": TypedContractEvent<
      AllocationUpdatedEvent.InputTuple,
      AllocationUpdatedEvent.OutputTuple,
      AllocationUpdatedEvent.OutputObject
    >;
    AllocationUpdated: TypedContractEvent<
      AllocationUpdatedEvent.InputTuple,
      AllocationUpdatedEvent.OutputTuple,
      AllocationUpdatedEvent.OutputObject
    >;

    "LendingModuleUpdated(address)": TypedContractEvent<
      LendingModuleUpdatedEvent.InputTuple,
      LendingModuleUpdatedEvent.OutputTuple,
      LendingModuleUpdatedEvent.OutputObject
    >;
    LendingModuleUpdated: TypedContractEvent<
      LendingModuleUpdatedEvent.InputTuple,
      LendingModuleUpdatedEvent.OutputTuple,
      LendingModuleUpdatedEvent.OutputObject
    >;

    "OptimizerActivated(bool)": TypedContractEvent<
      OptimizerActivatedEvent.InputTuple,
      OptimizerActivatedEvent.OutputTuple,
      OptimizerActivatedEvent.OutputObject
    >;
    OptimizerActivated: TypedContractEvent<
      OptimizerActivatedEvent.InputTuple,
      OptimizerActivatedEvent.OutputTuple,
      OptimizerActivatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RebalanceExecuted(uint256,uint256,uint256,bool)": TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;
    RebalanceExecuted: TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    "YieldUpdated(uint256,uint256,uint256)": TypedContractEvent<
      YieldUpdatedEvent.InputTuple,
      YieldUpdatedEvent.OutputTuple,
      YieldUpdatedEvent.OutputObject
    >;
    YieldUpdated: TypedContractEvent<
      YieldUpdatedEvent.InputTuple,
      YieldUpdatedEvent.OutputTuple,
      YieldUpdatedEvent.OutputObject
    >;
  };
}
