/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IHLEALMStateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getVariance"
      | "kImpact"
      | "kVol"
      | "token0"
      | "token0Index"
      | "token1"
      | "token1Index"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getVariance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kImpact", values?: undefined): string;
  encodeFunctionData(functionFragment: "kVol", values?: undefined): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "token0Index",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "token1Index",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getVariance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kImpact", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kVol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "token0Index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "token1Index",
    data: BytesLike
  ): Result;
}

export interface IHLEALMState extends BaseContract {
  connect(runner?: ContractRunner | null): IHLEALMState;
  waitForDeployment(): Promise<this>;

  interface: IHLEALMStateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getVariance: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fastVar: bigint;
        slowVar: bigint;
        maxVar: bigint;
      }
    ],
    "view"
  >;

  kImpact: TypedContractMethod<[], [bigint], "view">;

  kVol: TypedContractMethod<[], [bigint], "view">;

  token0: TypedContractMethod<[], [string], "view">;

  token0Index: TypedContractMethod<[], [bigint], "view">;

  token1: TypedContractMethod<[], [string], "view">;

  token1Index: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getVariance"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fastVar: bigint;
        slowVar: bigint;
        maxVar: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "kImpact"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "kVol"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token0Index"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token1Index"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
