/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILendingModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canOperate"
      | "getSuppliedAmount"
      | "getTokenIndex"
      | "pause"
      | "previewSupplyAction"
      | "previewWithdrawAction"
      | "rescueTokens"
      | "setConfig"
      | "setStrategist"
      | "setTokenIndex"
      | "setTokenIndices"
      | "supply"
      | "supplyToLending"
      | "unpause"
      | "withdraw"
      | "withdrawFromLending"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfigUpdated"
      | "Paused"
      | "StrategistUpdated"
      | "SupplyToLending"
      | "TokenIndexSet"
      | "Unpaused"
      | "WithdrawFromLending"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canOperate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSuppliedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewSupplyAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewWithdrawAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenIndices",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyToLending",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromLending",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "canOperate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSuppliedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewSupplyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewWithdrawAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStrategist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenIndices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplyToLending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromLending",
    data: BytesLike
  ): Result;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [
    minSupplyAmount: BigNumberish,
    cooldownBlocks: BigNumberish
  ];
  export type OutputTuple = [minSupplyAmount: bigint, cooldownBlocks: bigint];
  export interface OutputObject {
    minSupplyAmount: bigint;
    cooldownBlocks: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategistUpdatedEvent {
  export type InputTuple = [
    oldStrategist: AddressLike,
    newStrategist: AddressLike
  ];
  export type OutputTuple = [oldStrategist: string, newStrategist: string];
  export interface OutputObject {
    oldStrategist: string;
    newStrategist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyToLendingEvent {
  export type InputTuple = [
    token: AddressLike,
    tokenIndex: BigNumberish,
    amount: BigNumberish,
    weiAmount: BigNumberish,
    sender: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    tokenIndex: bigint,
    amount: bigint,
    weiAmount: bigint,
    sender: string
  ];
  export interface OutputObject {
    token: string;
    tokenIndex: bigint;
    amount: bigint;
    weiAmount: bigint;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenIndexSetEvent {
  export type InputTuple = [token: AddressLike, tokenIndex: BigNumberish];
  export type OutputTuple = [token: string, tokenIndex: bigint];
  export interface OutputObject {
    token: string;
    tokenIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawFromLendingEvent {
  export type InputTuple = [
    token: AddressLike,
    tokenIndex: BigNumberish,
    amount: BigNumberish,
    weiAmount: BigNumberish,
    sender: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    tokenIndex: bigint,
    amount: bigint,
    weiAmount: bigint,
    sender: string
  ];
  export interface OutputObject {
    token: string;
    tokenIndex: bigint;
    amount: bigint;
    weiAmount: bigint;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILendingModule extends BaseContract {
  connect(runner?: ContractRunner | null): ILendingModule;
  waitForDeployment(): Promise<this>;

  interface: ILendingModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canOperate: TypedContractMethod<[], [boolean], "view">;

  getSuppliedAmount: TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;

  getTokenIndex: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  previewSupplyAction: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [string],
    "view"
  >;

  previewWithdrawAction: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [string],
    "view"
  >;

  rescueTokens: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<
    [_minSupplyAmount: BigNumberish, _cooldownBlocks: BigNumberish],
    [void],
    "nonpayable"
  >;

  setStrategist: TypedContractMethod<
    [_newStrategist: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenIndex: TypedContractMethod<
    [token: AddressLike, tokenIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenIndices: TypedContractMethod<
    [tokens: AddressLike[], indices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  supply: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  supplyToLending: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFromLending: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canOperate"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSuppliedAmount"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenIndex"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "previewSupplyAction"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "previewWithdrawAction"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "rescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<
    [_minSupplyAmount: BigNumberish, _cooldownBlocks: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setStrategist"
  ): TypedContractMethod<[_newStrategist: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenIndex"
  ): TypedContractMethod<
    [token: AddressLike, tokenIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenIndices"
  ): TypedContractMethod<
    [tokens: AddressLike[], indices: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplyToLending"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFromLending"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "StrategistUpdated"
  ): TypedContractEvent<
    StrategistUpdatedEvent.InputTuple,
    StrategistUpdatedEvent.OutputTuple,
    StrategistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyToLending"
  ): TypedContractEvent<
    SupplyToLendingEvent.InputTuple,
    SupplyToLendingEvent.OutputTuple,
    SupplyToLendingEvent.OutputObject
  >;
  getEvent(
    key: "TokenIndexSet"
  ): TypedContractEvent<
    TokenIndexSetEvent.InputTuple,
    TokenIndexSetEvent.OutputTuple,
    TokenIndexSetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawFromLending"
  ): TypedContractEvent<
    WithdrawFromLendingEvent.InputTuple,
    WithdrawFromLendingEvent.OutputTuple,
    WithdrawFromLendingEvent.OutputObject
  >;

  filters: {
    "ConfigUpdated(uint256,uint256)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "StrategistUpdated(address,address)": TypedContractEvent<
      StrategistUpdatedEvent.InputTuple,
      StrategistUpdatedEvent.OutputTuple,
      StrategistUpdatedEvent.OutputObject
    >;
    StrategistUpdated: TypedContractEvent<
      StrategistUpdatedEvent.InputTuple,
      StrategistUpdatedEvent.OutputTuple,
      StrategistUpdatedEvent.OutputObject
    >;

    "SupplyToLending(address,uint64,uint256,uint64,address)": TypedContractEvent<
      SupplyToLendingEvent.InputTuple,
      SupplyToLendingEvent.OutputTuple,
      SupplyToLendingEvent.OutputObject
    >;
    SupplyToLending: TypedContractEvent<
      SupplyToLendingEvent.InputTuple,
      SupplyToLendingEvent.OutputTuple,
      SupplyToLendingEvent.OutputObject
    >;

    "TokenIndexSet(address,uint64)": TypedContractEvent<
      TokenIndexSetEvent.InputTuple,
      TokenIndexSetEvent.OutputTuple,
      TokenIndexSetEvent.OutputObject
    >;
    TokenIndexSet: TypedContractEvent<
      TokenIndexSetEvent.InputTuple,
      TokenIndexSetEvent.OutputTuple,
      TokenIndexSetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WithdrawFromLending(address,uint64,uint256,uint64,address)": TypedContractEvent<
      WithdrawFromLendingEvent.InputTuple,
      WithdrawFromLendingEvent.OutputTuple,
      WithdrawFromLendingEvent.OutputObject
    >;
    WithdrawFromLending: TypedContractEvent<
      WithdrawFromLendingEvent.InputTuple,
      WithdrawFromLendingEvent.OutputTuple,
      WithdrawFromLendingEvent.OutputObject
    >;
  };
}
