/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ILendingOrchestrator {
  export type RebalanceConfigStruct = {
    targetAmmShareBps: BigNumberish;
    maxRebalanceAmount: BigNumberish;
    cooldownBlocks: BigNumberish;
    validator: AddressLike;
  };

  export type RebalanceConfigStructOutput = [
    targetAmmShareBps: bigint,
    maxRebalanceAmount: bigint,
    cooldownBlocks: bigint,
    validator: string
  ] & {
    targetAmmShareBps: bigint;
    maxRebalanceAmount: bigint;
    cooldownBlocks: bigint;
    validator: string;
  };
}

export interface ILendingOrchestratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateRebalanceAmount"
      | "canRebalance"
      | "getConfig"
      | "rebalanceFromStaking"
      | "rebalanceToStaking"
      | "setConfig"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfigUpdated"
      | "RebalanceFromStaking"
      | "RebalanceToStaking"
      | "StrategistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateRebalanceAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canRebalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rebalanceFromStaking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceToStaking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [ILendingOrchestrator.RebalanceConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRebalanceAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceFromStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceToStaking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [config: ILendingOrchestrator.RebalanceConfigStruct];
  export type OutputTuple = [
    config: ILendingOrchestrator.RebalanceConfigStructOutput
  ];
  export interface OutputObject {
    config: ILendingOrchestrator.RebalanceConfigStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceFromStakingEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceToStakingEvent {
  export type InputTuple = [amount: BigNumberish, validator: AddressLike];
  export type OutputTuple = [amount: bigint, validator: string];
  export interface OutputObject {
    amount: bigint;
    validator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategistUpdatedEvent {
  export type InputTuple = [
    oldStrategist: AddressLike,
    newStrategist: AddressLike
  ];
  export type OutputTuple = [oldStrategist: string, newStrategist: string];
  export interface OutputObject {
    oldStrategist: string;
    newStrategist: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILendingOrchestrator extends BaseContract {
  connect(runner?: ContractRunner | null): ILendingOrchestrator;
  waitForDeployment(): Promise<this>;

  interface: ILendingOrchestratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateRebalanceAmount: TypedContractMethod<
    [],
    [[bigint, bigint] & { toStaking: bigint; fromStaking: bigint }],
    "view"
  >;

  canRebalance: TypedContractMethod<[], [boolean], "view">;

  getConfig: TypedContractMethod<
    [],
    [ILendingOrchestrator.RebalanceConfigStructOutput],
    "view"
  >;

  rebalanceFromStaking: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  rebalanceToStaking: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setConfig: TypedContractMethod<
    [config: ILendingOrchestrator.RebalanceConfigStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateRebalanceAmount"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { toStaking: bigint; fromStaking: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "canRebalance"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getConfig"
  ): TypedContractMethod<
    [],
    [ILendingOrchestrator.RebalanceConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "rebalanceFromStaking"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rebalanceToStaking"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<
    [config: ILendingOrchestrator.RebalanceConfigStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceFromStaking"
  ): TypedContractEvent<
    RebalanceFromStakingEvent.InputTuple,
    RebalanceFromStakingEvent.OutputTuple,
    RebalanceFromStakingEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceToStaking"
  ): TypedContractEvent<
    RebalanceToStakingEvent.InputTuple,
    RebalanceToStakingEvent.OutputTuple,
    RebalanceToStakingEvent.OutputObject
  >;
  getEvent(
    key: "StrategistUpdated"
  ): TypedContractEvent<
    StrategistUpdatedEvent.InputTuple,
    StrategistUpdatedEvent.OutputTuple,
    StrategistUpdatedEvent.OutputObject
  >;

  filters: {
    "ConfigUpdated(tuple)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "RebalanceFromStaking(uint256)": TypedContractEvent<
      RebalanceFromStakingEvent.InputTuple,
      RebalanceFromStakingEvent.OutputTuple,
      RebalanceFromStakingEvent.OutputObject
    >;
    RebalanceFromStaking: TypedContractEvent<
      RebalanceFromStakingEvent.InputTuple,
      RebalanceFromStakingEvent.OutputTuple,
      RebalanceFromStakingEvent.OutputObject
    >;

    "RebalanceToStaking(uint256,address)": TypedContractEvent<
      RebalanceToStakingEvent.InputTuple,
      RebalanceToStakingEvent.OutputTuple,
      RebalanceToStakingEvent.OutputObject
    >;
    RebalanceToStaking: TypedContractEvent<
      RebalanceToStakingEvent.InputTuple,
      RebalanceToStakingEvent.OutputTuple,
      RebalanceToStakingEvent.OutputObject
    >;

    "StrategistUpdated(address,address)": TypedContractEvent<
      StrategistUpdatedEvent.InputTuple,
      StrategistUpdatedEvent.OutputTuple,
      StrategistUpdatedEvent.OutputObject
    >;
    StrategistUpdated: TypedContractEvent<
      StrategistUpdatedEvent.InputTuple,
      StrategistUpdatedEvent.OutputTuple,
      StrategistUpdatedEvent.OutputObject
    >;
  };
}
