/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOracleModule {
  export type OracleSnapshotStruct = {
    priceX96: BigNumberish;
    l1BlockNumber: BigNumberish;
    timestamp: BigNumberish;
  };

  export type OracleSnapshotStructOutput = [
    priceX96: bigint,
    l1BlockNumber: bigint,
    timestamp: bigint
  ] & { priceX96: bigint; l1BlockNumber: bigint; timestamp: bigint };
}

export interface IOracleModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getCurrentPrice"
      | "getLatestSnapshot"
      | "isPriceValid"
      | "snapshotPrice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestSnapshot",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPriceValid",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "snapshotPrice",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPriceValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "snapshotPrice",
    data: BytesLike
  ): Result;
}

export interface IOracleModule extends BaseContract {
  connect(runner?: ContractRunner | null): IOracleModule;
  waitForDeployment(): Promise<this>;

  interface: IOracleModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getCurrentPrice: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [bigint],
    "view"
  >;

  getLatestSnapshot: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [IOracleModule.OracleSnapshotStructOutput],
    "view"
  >;

  isPriceValid: TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      priceX96: BigNumberish,
      maxDeviationBps: BigNumberish
    ],
    [boolean],
    "view"
  >;

  snapshotPrice: TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [IOracleModule.OracleSnapshotStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestSnapshot"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [IOracleModule.OracleSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPriceValid"
  ): TypedContractMethod<
    [
      token0: AddressLike,
      token1: AddressLike,
      priceX96: BigNumberish,
      maxDeviationBps: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "snapshotPrice"
  ): TypedContractMethod<
    [token0: AddressLike, token1: AddressLike],
    [IOracleModule.OracleSnapshotStructOutput],
    "nonpayable"
  >;

  filters: {};
}
