/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IQuoteValidator {
  export type QuoteStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    amountOutMin: BigNumberish;
    executionPriceX96: BigNumberish;
    oracleSnapshotPriceX96: BigNumberish;
    oracleL1Block: BigNumberish;
    expirationBlock: BigNumberish;
    intendedUser: AddressLike;
    maxDeviationBps: BigNumberish;
    quoteId: BytesLike;
  };

  export type QuoteStructOutput = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOutMin: bigint,
    executionPriceX96: bigint,
    oracleSnapshotPriceX96: bigint,
    oracleL1Block: bigint,
    expirationBlock: bigint,
    intendedUser: string,
    maxDeviationBps: bigint,
    quoteId: string
  ] & {
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOutMin: bigint;
    executionPriceX96: bigint;
    oracleSnapshotPriceX96: bigint;
    oracleL1Block: bigint;
    expirationBlock: bigint;
    intendedUser: string;
    maxDeviationBps: bigint;
    quoteId: string;
  };
}

export interface IQuoteValidatorInterface extends Interface {
  getFunction(
    nameOrSignature: "executeQuote" | "hasOracleDrifted" | "validateQuote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "QuoteExecuted" | "QuoteRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeQuote",
    values: [IQuoteValidator.QuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "hasOracleDrifted",
    values: [IQuoteValidator.QuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateQuote",
    values: [IQuoteValidator.QuoteStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasOracleDrifted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateQuote",
    data: BytesLike
  ): Result;
}

export namespace QuoteExecutedEvent {
  export type InputTuple = [
    quoteId: BytesLike,
    user: AddressLike,
    tokenIn: AddressLike,
    tokenOut: AddressLike,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: string,
    user: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    quoteId: string;
    user: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteRejectedEvent {
  export type InputTuple = [quoteId: BytesLike, reason: string];
  export type OutputTuple = [quoteId: string, reason: string];
  export interface OutputObject {
    quoteId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IQuoteValidator extends BaseContract {
  connect(runner?: ContractRunner | null): IQuoteValidator;
  waitForDeployment(): Promise<this>;

  interface: IQuoteValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeQuote: TypedContractMethod<
    [quote: IQuoteValidator.QuoteStruct],
    [bigint],
    "nonpayable"
  >;

  hasOracleDrifted: TypedContractMethod<
    [quote: IQuoteValidator.QuoteStruct],
    [boolean],
    "view"
  >;

  validateQuote: TypedContractMethod<
    [quote: IQuoteValidator.QuoteStruct],
    [[boolean, string] & { valid: boolean; reason: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeQuote"
  ): TypedContractMethod<
    [quote: IQuoteValidator.QuoteStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasOracleDrifted"
  ): TypedContractMethod<
    [quote: IQuoteValidator.QuoteStruct],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateQuote"
  ): TypedContractMethod<
    [quote: IQuoteValidator.QuoteStruct],
    [[boolean, string] & { valid: boolean; reason: string }],
    "view"
  >;

  getEvent(
    key: "QuoteExecuted"
  ): TypedContractEvent<
    QuoteExecutedEvent.InputTuple,
    QuoteExecutedEvent.OutputTuple,
    QuoteExecutedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteRejected"
  ): TypedContractEvent<
    QuoteRejectedEvent.InputTuple,
    QuoteRejectedEvent.OutputTuple,
    QuoteRejectedEvent.OutputObject
  >;

  filters: {
    "QuoteExecuted(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      QuoteExecutedEvent.InputTuple,
      QuoteExecutedEvent.OutputTuple,
      QuoteExecutedEvent.OutputObject
    >;
    QuoteExecuted: TypedContractEvent<
      QuoteExecutedEvent.InputTuple,
      QuoteExecutedEvent.OutputTuple,
      QuoteExecutedEvent.OutputObject
    >;

    "QuoteRejected(bytes32,string)": TypedContractEvent<
      QuoteRejectedEvent.InputTuple,
      QuoteRejectedEvent.OutputTuple,
      QuoteRejectedEvent.OutputObject
    >;
    QuoteRejected: TypedContractEvent<
      QuoteRejectedEvent.InputTuple,
      QuoteRejectedEvent.OutputTuple,
      QuoteRejectedEvent.OutputObject
    >;
  };
}
