/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFlashBorrower } from "./IFlashBorrower";
export type { ISovereignPool } from "./ISovereignPool";
export type { IValantisPool } from "./IValantisPool";
