/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export type SovereignPoolSwapContextDataStruct = {
  externalContext: BytesLike;
  verifierContext: BytesLike;
  swapCallbackContext: BytesLike;
  swapFeeModuleContext: BytesLike;
};

export type SovereignPoolSwapContextDataStructOutput = [
  externalContext: string,
  verifierContext: string,
  swapCallbackContext: string,
  swapFeeModuleContext: string
] & {
  externalContext: string;
  verifierContext: string;
  swapCallbackContext: string;
  swapFeeModuleContext: string;
};

export type SovereignPoolSwapParamsStruct = {
  isSwapCallback: boolean;
  isZeroToOne: boolean;
  amountIn: BigNumberish;
  amountOutMin: BigNumberish;
  deadline: BigNumberish;
  recipient: AddressLike;
  swapTokenOut: AddressLike;
  swapContext: SovereignPoolSwapContextDataStruct;
};

export type SovereignPoolSwapParamsStructOutput = [
  isSwapCallback: boolean,
  isZeroToOne: boolean,
  amountIn: bigint,
  amountOutMin: bigint,
  deadline: bigint,
  recipient: string,
  swapTokenOut: string,
  swapContext: SovereignPoolSwapContextDataStructOutput
] & {
  isSwapCallback: boolean;
  isZeroToOne: boolean;
  amountIn: bigint;
  amountOutMin: bigint;
  deadline: bigint;
  recipient: string;
  swapTokenOut: string;
  swapContext: SovereignPoolSwapContextDataStructOutput;
};

export interface ISovereignPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "alm"
      | "claimPoolManagerFees"
      | "claimProtocolFees"
      | "defaultSwapFeeBips"
      | "depositLiquidity"
      | "flashLoan"
      | "gauge"
      | "getPoolManagerFees"
      | "getReserves"
      | "getTokens"
      | "isLocked"
      | "isRebaseTokenPool"
      | "poolManager"
      | "poolManagerFeeBips"
      | "protocolFactory"
      | "setALM"
      | "setGauge"
      | "setPoolManager"
      | "setPoolManagerFeeBips"
      | "setSovereignOracle"
      | "setSwapFeeModule"
      | "sovereignOracleModule"
      | "sovereignVault"
      | "swap"
      | "swapFeeModule"
      | "swapFeeModuleUpdateTimestamp"
      | "token0"
      | "token1"
      | "verifierModule"
      | "withdrawLiquidity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ALMSet"
      | "DepositLiquidity"
      | "Flashloan"
      | "GaugeSet"
      | "PoolManagerFeeSet"
      | "PoolManagerFeesClaimed"
      | "PoolManagerSet"
      | "SovereignOracleSet"
      | "Swap"
      | "SwapFeeModuleSet"
      | "WithdrawLiquidity"
  ): EventFragment;

  encodeFunctionData(functionFragment: "alm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimPoolManagerFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimProtocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultSwapFeeBips",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositLiquidity",
    values: [BigNumberish, BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [boolean, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "gauge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPoolManagerFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTokens", values?: undefined): string;
  encodeFunctionData(functionFragment: "isLocked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isRebaseTokenPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolManagerFeeBips",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setALM", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setGauge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolManagerFeeBips",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSovereignOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSwapFeeModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sovereignOracleModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sovereignVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [SovereignPoolSwapParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapFeeModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapFeeModuleUpdateTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [BigNumberish, BigNumberish, AddressLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "alm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPoolManagerFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimProtocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultSwapFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gauge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolManagerFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isLocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRebaseTokenPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolManagerFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setALM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGauge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPoolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolManagerFeeBips",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSovereignOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSwapFeeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sovereignOracleModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sovereignVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapFeeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFeeModuleUpdateTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
}

export namespace ALMSetEvent {
  export type InputTuple = [alm: AddressLike];
  export type OutputTuple = [alm: string];
  export interface OutputObject {
    alm: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositLiquidityEvent {
  export type InputTuple = [amount0: BigNumberish, amount1: BigNumberish];
  export type OutputTuple = [amount0: bigint, amount1: bigint];
  export interface OutputObject {
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashloanEvent {
  export type InputTuple = [
    initiator: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    initiator: string,
    receiver: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    initiator: string;
    receiver: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GaugeSetEvent {
  export type InputTuple = [gauge: AddressLike];
  export type OutputTuple = [gauge: string];
  export interface OutputObject {
    gauge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolManagerFeeSetEvent {
  export type InputTuple = [poolManagerFeeBips: BigNumberish];
  export type OutputTuple = [poolManagerFeeBips: bigint];
  export interface OutputObject {
    poolManagerFeeBips: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolManagerFeesClaimedEvent {
  export type InputTuple = [amount0: BigNumberish, amount1: BigNumberish];
  export type OutputTuple = [amount0: bigint, amount1: bigint];
  export interface OutputObject {
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolManagerSetEvent {
  export type InputTuple = [poolManager: AddressLike];
  export type OutputTuple = [poolManager: string];
  export interface OutputObject {
    poolManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SovereignOracleSetEvent {
  export type InputTuple = [sovereignOracle: AddressLike];
  export type OutputTuple = [sovereignOracle: string];
  export interface OutputObject {
    sovereignOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    sender: AddressLike,
    isZeroToOne: boolean,
    amountIn: BigNumberish,
    fee: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    isZeroToOne: boolean,
    amountIn: bigint,
    fee: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    sender: string;
    isZeroToOne: boolean;
    amountIn: bigint;
    fee: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapFeeModuleSetEvent {
  export type InputTuple = [swapFeeModule: AddressLike];
  export type OutputTuple = [swapFeeModule: string];
  export interface OutputObject {
    swapFeeModule: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawLiquidityEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount0: bigint,
    amount1: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount0: bigint;
    amount1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISovereignPool extends BaseContract {
  connect(runner?: ContractRunner | null): ISovereignPool;
  waitForDeployment(): Promise<this>;

  interface: ISovereignPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  alm: TypedContractMethod<[], [string], "view">;

  claimPoolManagerFees: TypedContractMethod<
    [_feeProtocol0Bips: BigNumberish, _feeProtocol1Bips: BigNumberish],
    [
      [bigint, bigint] & {
        feePoolManager0Received: bigint;
        feePoolManager1Received: bigint;
      }
    ],
    "nonpayable"
  >;

  claimProtocolFees: TypedContractMethod<[], [[bigint, bigint]], "nonpayable">;

  defaultSwapFeeBips: TypedContractMethod<[], [bigint], "view">;

  depositLiquidity: TypedContractMethod<
    [
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _sender: AddressLike,
      _verificationContext: BytesLike,
      _depositData: BytesLike
    ],
    [[bigint, bigint] & { amount0Deposited: bigint; amount1Deposited: bigint }],
    "nonpayable"
  >;

  flashLoan: TypedContractMethod<
    [
      _isTokenZero: boolean,
      _receiver: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  gauge: TypedContractMethod<[], [string], "view">;

  getPoolManagerFees: TypedContractMethod<
    [],
    [[bigint, bigint] & { poolManagerFee0: bigint; poolManagerFee1: bigint }],
    "view"
  >;

  getReserves: TypedContractMethod<
    [],
    [[bigint, bigint] & { reserve0: bigint; reserve1: bigint }],
    "view"
  >;

  getTokens: TypedContractMethod<[], [string[]], "view">;

  isLocked: TypedContractMethod<[], [boolean], "view">;

  isRebaseTokenPool: TypedContractMethod<[], [boolean], "view">;

  poolManager: TypedContractMethod<[], [string], "view">;

  poolManagerFeeBips: TypedContractMethod<[], [bigint], "view">;

  protocolFactory: TypedContractMethod<[], [string], "view">;

  setALM: TypedContractMethod<[_alm: AddressLike], [void], "nonpayable">;

  setGauge: TypedContractMethod<[_gauge: AddressLike], [void], "nonpayable">;

  setPoolManager: TypedContractMethod<
    [_manager: AddressLike],
    [void],
    "nonpayable"
  >;

  setPoolManagerFeeBips: TypedContractMethod<
    [_poolManagerFeeBips: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSovereignOracle: TypedContractMethod<
    [sovereignOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setSwapFeeModule: TypedContractMethod<
    [_swapFeeModule: AddressLike],
    [void],
    "nonpayable"
  >;

  sovereignOracleModule: TypedContractMethod<[], [string], "view">;

  sovereignVault: TypedContractMethod<[], [string], "view">;

  swap: TypedContractMethod<
    [_swapParams: SovereignPoolSwapParamsStruct],
    [[bigint, bigint]],
    "nonpayable"
  >;

  swapFeeModule: TypedContractMethod<[], [string], "view">;

  swapFeeModuleUpdateTimestamp: TypedContractMethod<[], [bigint], "view">;

  token0: TypedContractMethod<[], [string], "view">;

  token1: TypedContractMethod<[], [string], "view">;

  verifierModule: TypedContractMethod<[], [string], "view">;

  withdrawLiquidity: TypedContractMethod<
    [
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _sender: AddressLike,
      _recipient: AddressLike,
      _verificationContext: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "alm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimPoolManagerFees"
  ): TypedContractMethod<
    [_feeProtocol0Bips: BigNumberish, _feeProtocol1Bips: BigNumberish],
    [
      [bigint, bigint] & {
        feePoolManager0Received: bigint;
        feePoolManager1Received: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimProtocolFees"
  ): TypedContractMethod<[], [[bigint, bigint]], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultSwapFeeBips"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositLiquidity"
  ): TypedContractMethod<
    [
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _sender: AddressLike,
      _verificationContext: BytesLike,
      _depositData: BytesLike
    ],
    [[bigint, bigint] & { amount0Deposited: bigint; amount1Deposited: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flashLoan"
  ): TypedContractMethod<
    [
      _isTokenZero: boolean,
      _receiver: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gauge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolManagerFees"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { poolManagerFee0: bigint; poolManagerFee1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { reserve0: bigint; reserve1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isLocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRebaseTokenPool"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "poolManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolManagerFeeBips"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setALM"
  ): TypedContractMethod<[_alm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGauge"
  ): TypedContractMethod<[_gauge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolManager"
  ): TypedContractMethod<[_manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolManagerFeeBips"
  ): TypedContractMethod<
    [_poolManagerFeeBips: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSovereignOracle"
  ): TypedContractMethod<[sovereignOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSwapFeeModule"
  ): TypedContractMethod<[_swapFeeModule: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sovereignOracleModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sovereignVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [_swapParams: SovereignPoolSwapParamsStruct],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapFeeModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapFeeModuleUpdateTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<
    [
      _amount0: BigNumberish,
      _amount1: BigNumberish,
      _sender: AddressLike,
      _recipient: AddressLike,
      _verificationContext: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ALMSet"
  ): TypedContractEvent<
    ALMSetEvent.InputTuple,
    ALMSetEvent.OutputTuple,
    ALMSetEvent.OutputObject
  >;
  getEvent(
    key: "DepositLiquidity"
  ): TypedContractEvent<
    DepositLiquidityEvent.InputTuple,
    DepositLiquidityEvent.OutputTuple,
    DepositLiquidityEvent.OutputObject
  >;
  getEvent(
    key: "Flashloan"
  ): TypedContractEvent<
    FlashloanEvent.InputTuple,
    FlashloanEvent.OutputTuple,
    FlashloanEvent.OutputObject
  >;
  getEvent(
    key: "GaugeSet"
  ): TypedContractEvent<
    GaugeSetEvent.InputTuple,
    GaugeSetEvent.OutputTuple,
    GaugeSetEvent.OutputObject
  >;
  getEvent(
    key: "PoolManagerFeeSet"
  ): TypedContractEvent<
    PoolManagerFeeSetEvent.InputTuple,
    PoolManagerFeeSetEvent.OutputTuple,
    PoolManagerFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "PoolManagerFeesClaimed"
  ): TypedContractEvent<
    PoolManagerFeesClaimedEvent.InputTuple,
    PoolManagerFeesClaimedEvent.OutputTuple,
    PoolManagerFeesClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PoolManagerSet"
  ): TypedContractEvent<
    PoolManagerSetEvent.InputTuple,
    PoolManagerSetEvent.OutputTuple,
    PoolManagerSetEvent.OutputObject
  >;
  getEvent(
    key: "SovereignOracleSet"
  ): TypedContractEvent<
    SovereignOracleSetEvent.InputTuple,
    SovereignOracleSetEvent.OutputTuple,
    SovereignOracleSetEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "SwapFeeModuleSet"
  ): TypedContractEvent<
    SwapFeeModuleSetEvent.InputTuple,
    SwapFeeModuleSetEvent.OutputTuple,
    SwapFeeModuleSetEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawLiquidity"
  ): TypedContractEvent<
    WithdrawLiquidityEvent.InputTuple,
    WithdrawLiquidityEvent.OutputTuple,
    WithdrawLiquidityEvent.OutputObject
  >;

  filters: {
    "ALMSet(address)": TypedContractEvent<
      ALMSetEvent.InputTuple,
      ALMSetEvent.OutputTuple,
      ALMSetEvent.OutputObject
    >;
    ALMSet: TypedContractEvent<
      ALMSetEvent.InputTuple,
      ALMSetEvent.OutputTuple,
      ALMSetEvent.OutputObject
    >;

    "DepositLiquidity(uint256,uint256)": TypedContractEvent<
      DepositLiquidityEvent.InputTuple,
      DepositLiquidityEvent.OutputTuple,
      DepositLiquidityEvent.OutputObject
    >;
    DepositLiquidity: TypedContractEvent<
      DepositLiquidityEvent.InputTuple,
      DepositLiquidityEvent.OutputTuple,
      DepositLiquidityEvent.OutputObject
    >;

    "Flashloan(address,address,uint256,address)": TypedContractEvent<
      FlashloanEvent.InputTuple,
      FlashloanEvent.OutputTuple,
      FlashloanEvent.OutputObject
    >;
    Flashloan: TypedContractEvent<
      FlashloanEvent.InputTuple,
      FlashloanEvent.OutputTuple,
      FlashloanEvent.OutputObject
    >;

    "GaugeSet(address)": TypedContractEvent<
      GaugeSetEvent.InputTuple,
      GaugeSetEvent.OutputTuple,
      GaugeSetEvent.OutputObject
    >;
    GaugeSet: TypedContractEvent<
      GaugeSetEvent.InputTuple,
      GaugeSetEvent.OutputTuple,
      GaugeSetEvent.OutputObject
    >;

    "PoolManagerFeeSet(uint256)": TypedContractEvent<
      PoolManagerFeeSetEvent.InputTuple,
      PoolManagerFeeSetEvent.OutputTuple,
      PoolManagerFeeSetEvent.OutputObject
    >;
    PoolManagerFeeSet: TypedContractEvent<
      PoolManagerFeeSetEvent.InputTuple,
      PoolManagerFeeSetEvent.OutputTuple,
      PoolManagerFeeSetEvent.OutputObject
    >;

    "PoolManagerFeesClaimed(uint256,uint256)": TypedContractEvent<
      PoolManagerFeesClaimedEvent.InputTuple,
      PoolManagerFeesClaimedEvent.OutputTuple,
      PoolManagerFeesClaimedEvent.OutputObject
    >;
    PoolManagerFeesClaimed: TypedContractEvent<
      PoolManagerFeesClaimedEvent.InputTuple,
      PoolManagerFeesClaimedEvent.OutputTuple,
      PoolManagerFeesClaimedEvent.OutputObject
    >;

    "PoolManagerSet(address)": TypedContractEvent<
      PoolManagerSetEvent.InputTuple,
      PoolManagerSetEvent.OutputTuple,
      PoolManagerSetEvent.OutputObject
    >;
    PoolManagerSet: TypedContractEvent<
      PoolManagerSetEvent.InputTuple,
      PoolManagerSetEvent.OutputTuple,
      PoolManagerSetEvent.OutputObject
    >;

    "SovereignOracleSet(address)": TypedContractEvent<
      SovereignOracleSetEvent.InputTuple,
      SovereignOracleSetEvent.OutputTuple,
      SovereignOracleSetEvent.OutputObject
    >;
    SovereignOracleSet: TypedContractEvent<
      SovereignOracleSetEvent.InputTuple,
      SovereignOracleSetEvent.OutputTuple,
      SovereignOracleSetEvent.OutputObject
    >;

    "Swap(address,bool,uint256,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "SwapFeeModuleSet(address)": TypedContractEvent<
      SwapFeeModuleSetEvent.InputTuple,
      SwapFeeModuleSetEvent.OutputTuple,
      SwapFeeModuleSetEvent.OutputObject
    >;
    SwapFeeModuleSet: TypedContractEvent<
      SwapFeeModuleSetEvent.InputTuple,
      SwapFeeModuleSetEvent.OutputTuple,
      SwapFeeModuleSetEvent.OutputObject
    >;

    "WithdrawLiquidity(address,uint256,uint256)": TypedContractEvent<
      WithdrawLiquidityEvent.InputTuple,
      WithdrawLiquidityEvent.OutputTuple,
      WithdrawLiquidityEvent.OutputObject
    >;
    WithdrawLiquidity: TypedContractEvent<
      WithdrawLiquidityEvent.InputTuple,
      WithdrawLiquidityEvent.OutputTuple,
      WithdrawLiquidityEvent.OutputObject
    >;
  };
}
