/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IValantisPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimPoolManagerFees"
      | "claimProtocolFees"
      | "flashLoan"
      | "setGauge"
      | "token0"
      | "token1"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Flashloan"): EventFragment;

  encodeFunctionData(
    functionFragment: "claimPoolManagerFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimProtocolFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [boolean, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGauge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "claimPoolManagerFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimProtocolFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGauge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
}

export namespace FlashloanEvent {
  export type InputTuple = [
    initiator: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    initiator: string,
    receiver: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    initiator: string;
    receiver: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IValantisPool extends BaseContract {
  connect(runner?: ContractRunner | null): IValantisPool;
  waitForDeployment(): Promise<this>;

  interface: IValantisPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimPoolManagerFees: TypedContractMethod<
    [_feeProtocol0Bips: BigNumberish, _feeProtocol1Bips: BigNumberish],
    [
      [bigint, bigint] & {
        feePoolManager0Received: bigint;
        feePoolManager1Received: bigint;
      }
    ],
    "nonpayable"
  >;

  claimProtocolFees: TypedContractMethod<[], [[bigint, bigint]], "nonpayable">;

  flashLoan: TypedContractMethod<
    [
      _isTokenZero: boolean,
      _receiver: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setGauge: TypedContractMethod<[_gauge: AddressLike], [void], "nonpayable">;

  token0: TypedContractMethod<[], [string], "view">;

  token1: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimPoolManagerFees"
  ): TypedContractMethod<
    [_feeProtocol0Bips: BigNumberish, _feeProtocol1Bips: BigNumberish],
    [
      [bigint, bigint] & {
        feePoolManager0Received: bigint;
        feePoolManager1Received: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimProtocolFees"
  ): TypedContractMethod<[], [[bigint, bigint]], "nonpayable">;
  getFunction(
    nameOrSignature: "flashLoan"
  ): TypedContractMethod<
    [
      _isTokenZero: boolean,
      _receiver: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGauge"
  ): TypedContractMethod<[_gauge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token1"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Flashloan"
  ): TypedContractEvent<
    FlashloanEvent.InputTuple,
    FlashloanEvent.OutputTuple,
    FlashloanEvent.OutputObject
  >;

  filters: {
    "Flashloan(address,address,uint256,address)": TypedContractEvent<
      FlashloanEvent.InputTuple,
      FlashloanEvent.OutputTuple,
      FlashloanEvent.OutputObject
    >;
    Flashloan: TypedContractEvent<
      FlashloanEvent.InputTuple,
      FlashloanEvent.OutputTuple,
      FlashloanEvent.OutputObject
    >;
  };
}
