/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hyperEvmLib from "./hyper-evm-lib";
export type { hyperEvmLib };
import type * as valantisCore from "./valantis-core";
export type { valantisCore };
