/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwapFeeModule,
  ISwapFeeModuleInterface,
} from "../../../../../../../lib/valantis-core/src/swap-fee-modules/interfaces/ISwapFeeModule.sol/ISwapFeeModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_effectiveFee",
        type: "uint256",
      },
      {
        internalType: "int24",
        name: "_spotPriceTick",
        type: "int24",
      },
      {
        internalType: "uint256",
        name: "_amountInUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountOut",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "feeInBips",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "internalContext",
            type: "bytes",
          },
        ],
        internalType: "struct SwapFeeModuleData",
        name: "_swapFeeModuleData",
        type: "tuple",
      },
    ],
    name: "callbackOnSwapEnd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_effectiveFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountInUsed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amountOut",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "feeInBips",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "internalContext",
            type: "bytes",
          },
        ],
        internalType: "struct SwapFeeModuleData",
        name: "_swapFeeModuleData",
        type: "tuple",
      },
    ],
    name: "callbackOnSwapEnd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "_tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_swapFeeModuleContext",
        type: "bytes",
      },
    ],
    name: "getSwapFeeInBips",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "feeInBips",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "internalContext",
            type: "bytes",
          },
        ],
        internalType: "struct SwapFeeModuleData",
        name: "swapFeeModuleData",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwapFeeModule__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapFeeModuleInterface {
    return new Interface(_abi) as ISwapFeeModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISwapFeeModule {
    return new Contract(address, _abi, runner) as unknown as ISwapFeeModule;
  }
}
