/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwapFeeModuleMinimal,
  ISwapFeeModuleMinimalInterface,
} from "../../../../../../../lib/valantis-core/src/swap-fee-modules/interfaces/ISwapFeeModule.sol/ISwapFeeModuleMinimal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "_tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_swapFeeModuleContext",
        type: "bytes",
      },
    ],
    name: "getSwapFeeInBips",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "feeInBips",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "internalContext",
            type: "bytes",
          },
        ],
        internalType: "struct SwapFeeModuleData",
        name: "swapFeeModuleData",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwapFeeModuleMinimal__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapFeeModuleMinimalInterface {
    return new Interface(_abi) as ISwapFeeModuleMinimalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISwapFeeModuleMinimal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISwapFeeModuleMinimal;
  }
}
