/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IHLEALMState,
  IHLEALMStateInterface,
} from "../../../../src/modules/HLEQuoter.sol/IHLEALMState";

const _abi = [
  {
    inputs: [],
    name: "getVariance",
    outputs: [
      {
        internalType: "uint256",
        name: "fastVar",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "slowVar",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxVar",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kImpact",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kVol",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0Index",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1Index",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IHLEALMState__factory {
  static readonly abi = _abi;
  static createInterface(): IHLEALMStateInterface {
    return new Interface(_abi) as IHLEALMStateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IHLEALMState {
    return new Contract(address, _abi, runner) as unknown as IHLEALMState;
  }
}
